export const tagTypes = {
  user: "user",
  specialization: "specialization",
  patient: "patient",
  admin: "admin",
  doctor: "doctor",
  doctorService: "doctorService",
  timeSlot: "timeSlot",
  doctorCreateService: "doctorCreateService",
  patientBookAppointment: "PatientBookAppointment",
  payment: "payment",
  doctorReview: "doctorReview",
  doctorEducation: "doctorEducation",
  doctorExperience: "doctorExperience",
};

export const tagTypesList = [
  tagTypes.user,
  tagTypes.specialization,
  tagTypes.patient,
  tagTypes.admin,
  tagTypes.doctor,
  tagTypes.doctorService,
  tagTypes.timeSlot,
  tagTypes.doctorCreateService,
  tagTypes.patientBookAppointment,
  tagTypes.payment,
  tagTypes.doctorReview,
  tagTypes.doctorEducation,
  tagTypes.doctorExperience,
];
